var searchData=
[
  ['c_0',['Guía: Entornos colaborativos para desarrollo en C',['../d1/d47/collab_env_guide.html',1,'cowork_section']]],
  ['c_3a_20secure_20deployment_20to_20edge_20nodes_1',['Use Case C: Secure Deployment to Edge Nodes',['../dd/dce/ghActionsCICD.html#autotoc_md139',1,'']]],
  ['cannonical_20array_2',['cannonical array',['../d4/d70/dictionary.html#autotoc_md113',1,'']]],
  ['canonical_20dictionary_20—_20signal_20quality_20validation_3',['Canonical Dictionary — Signal Quality Validation',['../d4/d70/dictionary.html',1,'cowork_section']]],
  ['case_20a_3a_20automated_20documentation_20sync_20cd_4',['Use Case A: Automated Documentation Sync (CD)',['../dd/dce/ghActionsCICD.html#autotoc_md137',1,'']]],
  ['case_20b_3a_20quality_20assurance_20schema_20check_20ci_5',['Use Case B: Quality Assurance &amp; Schema Check (CI)',['../dd/dce/ghActionsCICD.html#autotoc_md138',1,'']]],
  ['case_20c_3a_20secure_20deployment_20to_20edge_20nodes_6',['Use Case C: Secure Deployment to Edge Nodes',['../dd/dce/ghActionsCICD.html#autotoc_md139',1,'']]],
  ['cases_20for_20our_20repository_7',['3. Specific Use Cases for our Repository',['../dd/dce/ghActionsCICD.html#autotoc_md136',1,'']]],
  ['cd_8',['Use Case A: Automated Documentation Sync (CD)',['../dd/dce/ghActionsCICD.html#autotoc_md137',1,'']]],
  ['cd_20deploy_20yml_20tt_9',['CD: Documentation &amp; Deployment (&lt;tt&gt;.github/workflows/cd-deploy.yml&lt;/tt&gt;)',['../dd/dce/ghActionsCICD.html#autotoc_md143',1,'']]],
  ['cd_20for_20repository_10',['ADD CI/CD for repository',['../index.html#autotoc_md0',1,'']]],
  ['cd_20in_20ane_11',['1. Introduction to CI/CD in ANE',['../dd/dce/ghActionsCICD.html#autotoc_md131',1,'']]],
  ['cd_20pipeline_12',['4.2 CI/CD Pipeline',['../d4/d4b/software_readme_page.html#autotoc_md47',1,'']]],
  ['cd_3a_20documentation_20deployment_20tt_20github_20workflows_20cd_20deploy_20yml_20tt_13',['CD: Documentation &amp; Deployment (&lt;tt&gt;.github/workflows/cd-deploy.yml&lt;/tt&gt;)',['../dd/dce/ghActionsCICD.html#autotoc_md143',1,'']]],
  ['cd_3a_20guide_20for_20ane_20project_14',['GitHub Actions CI/CD: Guide for ANE Project',['../dd/dce/ghActionsCICD.html',1,'cowork_section']]],
  ['chatbots_20management_15',['Multiagent for chatbots management',['../d5/d65/agents_cli_management.html',1,'agents_cli_section']]],
  ['check_20ci_16',['Use Case B: Quality Assurance &amp; Schema Check (CI)',['../dd/dce/ghActionsCICD.html#autotoc_md138',1,'']]],
  ['checklist_17',['checklist',['../dc/d18/deployment_guide.html#autotoc_md169',1,'checklist'],['../df/d85/develop_standards.html#autotoc_md181',1,'INTEGRATION TEST CHECKLIST'],['../df/d85/develop_standards.html#autotoc_md182',1,'PERFORMANCE TEST CHECKLIST'],['../df/d85/develop_standards.html#autotoc_md180',1,'UNIT TEST CHECKLIST']]],
  ['ci_18',['Use Case B: Quality Assurance &amp; Schema Check (CI)',['../dd/dce/ghActionsCICD.html#autotoc_md138',1,'']]],
  ['ci_20cd_20for_20repository_19',['ADD CI/CD for repository',['../index.html#autotoc_md0',1,'']]],
  ['ci_20cd_20in_20ane_20',['1. Introduction to CI/CD in ANE',['../dd/dce/ghActionsCICD.html#autotoc_md131',1,'']]],
  ['ci_20cd_20pipeline_21',['4.2 CI/CD Pipeline',['../d4/d4b/software_readme_page.html#autotoc_md47',1,'']]],
  ['ci_20cd_3a_20guide_20for_20ane_20project_22',['GitHub Actions CI/CD: Guide for ANE Project',['../dd/dce/ghActionsCICD.html',1,'cowork_section']]],
  ['ci_20validation_20yml_20tt_23',['CI: Validation Workflow (&lt;tt&gt;.github/workflows/ci-validation.yml&lt;/tt&gt;)',['../dd/dce/ghActionsCICD.html#autotoc_md142',1,'']]],
  ['ci_3a_20validation_20workflow_20tt_20github_20workflows_20ci_20validation_20yml_20tt_24',['CI: Validation Workflow (&lt;tt&gt;.github/workflows/ci-validation.yml&lt;/tt&gt;)',['../dd/dce/ghActionsCICD.html#autotoc_md142',1,'']]],
  ['cli_25',['cli',['../index.html#autotoc_md2',1,'1. Getting Started: The Agents CLI'],['../da/d04/agents_cli_section.html',1,'AGENTS CLI']]],
  ['cli_20—_20guide_20for_20co_20workers_26',['Agents CLI — Guide for co-workers',['../index.html',1,'']]],
  ['cli_20—_20installation_20concepts_20and_20quickstart_27',['Gemini CLI — installation, concepts, and quickstart',['../da/d04/agents_cli_section.html#autotoc_md16',1,'']]],
  ['cli_20—_20installation_20get_20started_20and_20concepts_28',['Copilot CLI — installation, get started, and concepts',['../da/d04/agents_cli_section.html#autotoc_md15',1,'']]],
  ['cloning_20the_20repository_20using_20https_20or_20ssh_3a_20em_29',['&lt;em&gt;after cloning the repository using HTTPS or SSH:&lt;/em&gt;',['../dc/d18/deployment_guide.html#autotoc_md164',1,'']]],
  ['co_20workers_30',['Agents CLI — Guide for co-workers',['../index.html',1,'']]],
  ['code_20quality_20best_20practices_31',['Code Quality &amp; Best Practices',['../df/d85/develop_standards.html#autotoc_md170',1,'']]],
  ['codigo_32',['2. ESTÁNDARES DE CODIGO',['../df/d85/develop_standards.html#autotoc_md172',1,'']]],
  ['colaborativos_20para_20desarrollo_20en_20c_33',['Guía: Entornos colaborativos para desarrollo en C',['../d1/d47/collab_env_guide.html',1,'cowork_section']]],
  ['collaborative_20environments_20cowork_34',['3. Working Together: Collaborative Environments (COWORK)',['../index.html#autotoc_md7',1,'']]],
  ['commit_35',['BEFORE COMMIT',['../dc/d18/deployment_guide.html#autotoc_md167',1,'']]],
  ['component_20model_36',['2.2 Logical Design (Formal Component Model)',['../d4/d4b/software_readme_page.html#autotoc_md38',1,'']]],
  ['components_37',['components',['../d4/d4b/software_readme_page.html#autotoc_md40',1,'3. Core Technical Components'],['../d5/d1d/software_page.html#autotoc_md27',1,'3. Technical Components']]],
  ['computing_20processing_20sdr_20agent_38',['3.1 Edge Computing &amp; Processing (SDR Agent)',['../d4/d4b/software_readme_page.html#autotoc_md41',1,'']]],
  ['concepts_39',['concepts',['../dd/dce/ghActionsCICD.html#autotoc_md134',1,'2. Core Concepts'],['../da/d04/agents_cli_section.html#autotoc_md15',1,'Copilot CLI — installation, get started, and concepts']]],
  ['concepts_20and_20quickstart_40',['Gemini CLI — installation, concepts, and quickstart',['../da/d04/agents_cli_section.html#autotoc_md16',1,'']]],
  ['concepts_20why_20this_20tool_20is_20useful_41',['Concepts &amp; Why this tool is useful',['../da/d04/agents_cli_section.html#autotoc_md14',1,'']]],
  ['conceptual_42',['4. Proposed Workflow Structure (Conceptual)',['../dd/dce/ghActionsCICD.html#autotoc_md141',1,'']]],
  ['conceptual_20design_20high_20level_20idea_43',['1.1. Conceptual Design (high-level idea)',['../d5/d65/agents_cli_management.html#autotoc_md58',1,'']]],
  ['conceptual_20design_20high_20level_20intelligence_44',['2.1 Conceptual Design (High-Level Intelligence)',['../d4/d4b/software_readme_page.html#autotoc_md37',1,'']]],
  ['conditional_20fields_20required_20in_20specific_20routes_45',['Conditional Fields (required in specific routes)',['../d4/d70/dictionary.html#autotoc_md124',1,'']]],
  ['conditions_46',['2.6. FINALIZATION CONDITIONS',['../d5/d65/agents_cli_management.html#autotoc_md75',1,'']]],
  ['consistency_47',['Unit Consistency',['../d4/d70/dictionary.html#autotoc_md116',1,'']]],
  ['consistency_20and_20primary_20keys_48',['- &lt;strong&gt;DICTIONARY.md&lt;/strong&gt; — Table format (name | type | unit | description | source | importance); ~25 core variables; final notes on unit consistency and primary keys',['../d1/dcf/apiMaintenance.html#autotoc_md89',1,'']]],
  ['context_49',['2.3. CONTEXT',['../d5/d65/agents_cli_management.html#autotoc_md69',1,'']]],
  ['continue_20with_20the_20project_20structure_50',['1. Continue with the project structure',['../d5/d65/agents_cli_management.html#autotoc_md57',1,'']]],
  ['control_20version_51',['QUICK REFERENCE - CONTROL VERSION',['../dc/d18/deployment_guide.html#autotoc_md165',1,'']]],
  ['conventions_52',['Naming Conventions',['../d4/d70/dictionary.html#autotoc_md114',1,'']]],
  ['copilot_20cli_20—_20installation_20get_20started_20and_20concepts_53',['Copilot CLI — installation, get started, and concepts',['../da/d04/agents_cli_section.html#autotoc_md15',1,'']]],
  ['core_20concepts_54',['2. Core Concepts',['../dd/dce/ghActionsCICD.html#autotoc_md134',1,'']]],
  ['core_20documentation_55',['Core Documentation',['../d5/d1d/software_page.html#autotoc_md22',1,'']]],
  ['core_20technical_20components_56',['3. Core Technical Components',['../d4/d4b/software_readme_page.html#autotoc_md40',1,'']]],
  ['core_20variables_20final_20notes_20on_20unit_20consistency_20and_20primary_20keys_57',['- &lt;strong&gt;DICTIONARY.md&lt;/strong&gt; — Table format (name | type | unit | description | source | importance); ~25 core variables; final notes on unit consistency and primary keys',['../d1/dcf/apiMaintenance.html#autotoc_md89',1,'']]],
  ['cowork_58',['cowork',['../index.html#autotoc_md7',1,'3. Working Together: Collaborative Environments (COWORK)'],['../d6/dbd/cowork_section.html',1,'COWORK']]],
  ['criteria_59',['criteria',['../d1/dcf/apiMaintenance.html#autotoc_md80',1,'Goals &amp; Success Criteria'],['../d1/dcf/apiMaintenance.html#autotoc_md101',1,'Success Criteria'],['../d1/dcf/apiMaintenance.html#autotoc_md92',1,'Success Criteria'],['../d1/dcf/apiMaintenance.html#autotoc_md82',1,'Success Criteria']]],
  ['current_60',['Phase 1: Documentation &amp; Dictionary Finalization (CURRENT)',['../d1/dcf/apiMaintenance.html#autotoc_md86',1,'']]]
];
