var searchData=
[
  ['para_20desarrollo_20en_20c_0',['Guía: Entornos colaborativos para desarrollo en C',['../d1/d47/collab_env_guide.html',1,'cowork_section']]],
  ['para_20empezar_20un_20nuevo_20feature_1',['PARA EMPEZAR UN NUEVO FEATURE',['../dc/d18/deployment_guide.html#autotoc_md166',1,'']]],
  ['patterns_2',['Naming Patterns',['../d4/d70/dictionary.html#autotoc_md117',1,'']]],
  ['pep_20257_20google_20style_3',['2.3 DOCSTRINGS (PEP 257 + Google Style)',['../df/d85/develop_standards.html#autotoc_md175',1,'']]],
  ['pep_20484_4',['2.2 TYPE HINTS (PEP 484)',['../df/d85/develop_standards.html#autotoc_md174',1,'']]],
  ['pep_208_20formatting_20strong_5',['&lt;strong&gt;2.1 PEP 8 - Formatting&lt;/strong&gt;',['../df/d85/develop_standards.html#autotoc_md173',1,'']]],
  ['performance_20test_20checklist_6',['PERFORMANCE TEST CHECKLIST',['../df/d85/develop_standards.html#autotoc_md182',1,'']]],
  ['persistence_7',['3.3 Data Strategy &amp; Persistence',['../d4/d4b/software_readme_page.html#autotoc_md43',1,'']]],
  ['phase_201_3a_20documentation_20dictionary_20finalization_20current_8',['Phase 1: Documentation &amp; Dictionary Finalization (CURRENT)',['../d1/dcf/apiMaintenance.html#autotoc_md86',1,'']]],
  ['phase_202_3a_20data_20validation_20ingestion_20planned_9',['Phase 2: Data Validation &amp; Ingestion (PLANNED)',['../d1/dcf/apiMaintenance.html#autotoc_md90',1,'']]],
  ['phase_203_3a_20qa_20route_20implementation_20planned_10',['Phase 3: QA Route Implementation (PLANNED)',['../d1/dcf/apiMaintenance.html#autotoc_md94',1,'']]],
  ['phase_204_3a_20integration_20deployment_20planned_11',['Phase 4: Integration &amp; Deployment (PLANNED)',['../d1/dcf/apiMaintenance.html#autotoc_md99',1,'']]],
  ['physical_20design_20implementation_12',['1.3. Physical Design (implementation)',['../d5/d65/agents_cli_management.html#autotoc_md62',1,'']]],
  ['pipeline_13',['pipeline',['../d1/df9/arch_modules.html#autotoc_md159',1,'4. MÓDULO MAIN PIPELINE'],['../d4/d4b/software_readme_page.html#autotoc_md47',1,'4.2 CI/CD Pipeline']]],
  ['pipeline_20py_14',['Archivo: src/rf_spectrum/pipeline.py',['../d1/df9/arch_modules.html#autotoc_md160',1,'']]],
  ['planned_15',['planned',['../d1/dcf/apiMaintenance.html#autotoc_md90',1,'Phase 2: Data Validation &amp; Ingestion (PLANNED)'],['../d1/dcf/apiMaintenance.html#autotoc_md94',1,'Phase 3: QA Route Implementation (PLANNED)'],['../d1/dcf/apiMaintenance.html#autotoc_md99',1,'Phase 4: Integration &amp; Deployment (PLANNED)']]],
  ['practices_16',['practices',['../dd/dce/ghActionsCICD.html#autotoc_md147',1,'6. Security Best Practices'],['../df/d85/develop_standards.html#autotoc_md170',1,'Code Quality &amp; Best Practices'],['../d4/d70/dictionary.html#autotoc_md127',1,'Notes &amp; Best Practices'],['../da/d04/agents_cli_section.html#autotoc_md17',1,'Prompting best practices']]],
  ['present_17',['Required Fields (must always be present)',['../d4/d70/dictionary.html#autotoc_md123',1,'']]],
  ['primary_20goals_18',['Primary Goals',['../d1/dcf/apiMaintenance.html#autotoc_md81',1,'']]],
  ['primary_20keys_19',['- &lt;strong&gt;DICTIONARY.md&lt;/strong&gt; — Table format (name | type | unit | description | source | importance); ~25 core variables; final notes on unit consistency and primary keys',['../d1/dcf/apiMaintenance.html#autotoc_md89',1,'']]],
  ['primary_20keys_20for_20time_20series_20alignment_20',['Primary Keys (for time-series alignment)',['../d4/d70/dictionary.html#autotoc_md115',1,'']]],
  ['processing_20layer_21',['3. MODULO PROCESSING LAYER',['../d1/df9/arch_modules.html#autotoc_md156',1,'']]],
  ['processing_20noise_5ffloor_20py_22',['Archivo: src/rf_spectrum/processing/noise_floor.py',['../d1/df9/arch_modules.html#autotoc_md157',1,'']]],
  ['processing_20normalization_20py_23',['Archivo: src/rf_spectrum/processing/normalization.py',['../d1/df9/arch_modules.html#autotoc_md158',1,'']]],
  ['processing_20sdr_20agent_24',['3.1 Edge Computing &amp; Processing (SDR Agent)',['../d4/d4b/software_readme_page.html#autotoc_md41',1,'']]],
  ['professional_20engineering_3a_20software_20architecture_20api_25',['4. Professional Engineering: Software Architecture &amp; API',['../index.html#autotoc_md10',1,'']]],
  ['professional_20implementation_20deployment_26',['4. Professional Implementation &amp; Deployment',['../d4/d4b/software_readme_page.html#autotoc_md45',1,'']]],
  ['progress_20of_20the_20project_20this_20generate_20a_20specific_20structure_20on_20the_20project_20design_20_3a_27',['Divide the project into different roles according to the progress of the project, this generate a specific structure on the project design :',['../d5/d65/agents_cli_management.html#autotoc_md55',1,'']]],
  ['project_28',['GitHub Actions CI/CD: Guide for ANE Project',['../dd/dce/ghActionsCICD.html',1,'cowork_section']]],
  ['project_20into_20different_20roles_20according_20to_20the_20progress_20of_20the_20project_20this_20generate_20a_20specific_20structure_20on_20the_20project_20design_20_3a_29',['Divide the project into different roles according to the progress of the project, this generate a specific structure on the project design :',['../d5/d65/agents_cli_management.html#autotoc_md55',1,'']]],
  ['project_20structure_30',['1. Continue with the project structure',['../d5/d65/agents_cli_management.html#autotoc_md57',1,'']]],
  ['project_20vision_20strategic_20objectives_31',['Project Vision &amp; Strategic Objectives',['../d4/d4b/software_readme_page.html#autotoc_md29',1,'']]],
  ['prompting_20best_20practices_32',['Prompting best practices',['../da/d04/agents_cli_section.html#autotoc_md17',1,'']]],
  ['proposed_20workflow_20structure_20conceptual_33',['4. Proposed Workflow Structure (Conceptual)',['../dd/dce/ghActionsCICD.html#autotoc_md141',1,'']]],
  ['py_34',['py',['../d1/df9/arch_modules.html#autotoc_md155',1,'Archivo: src/rf_spectrum/data/validator.py'],['../d1/df9/arch_modules.html#autotoc_md160',1,'Archivo: src/rf_spectrum/pipeline.py'],['../d1/df9/arch_modules.html#autotoc_md157',1,'Archivo: src/rf_spectrum/processing/noise_floor.py'],['../d1/df9/arch_modules.html#autotoc_md158',1,'Archivo: src/rf_spectrum/processing/normalization.py']]],
  ['py_20tt_20strong_35',['&lt;strong&gt;Archivo: &lt;tt&gt;src/rf_spectrum/data/loader.py&lt;/tt&gt;&lt;/strong&gt;',['../d1/df9/arch_modules.html#autotoc_md154',1,'']]]
];
