var searchData=
[
  ['feature_0',['PARA EMPEZAR UN NUEVO FEATURE',['../dc/d18/deployment_guide.html#autotoc_md166',1,'']]],
  ['fields_20must_20always_20be_20present_1',['Required Fields (must always be present)',['../d4/d70/dictionary.html#autotoc_md123',1,'']]],
  ['fields_20required_20in_20specific_20routes_2',['Conditional Fields (required in specific routes)',['../d4/d70/dictionary.html#autotoc_md124',1,'']]],
  ['final_20notes_20on_20unit_20consistency_20and_20primary_20keys_3',['- &lt;strong&gt;DICTIONARY.md&lt;/strong&gt; — Table format (name | type | unit | description | source | importance); ~25 core variables; final notes on unit consistency and primary keys',['../d1/dcf/apiMaintenance.html#autotoc_md89',1,'']]],
  ['finalization_4',['6. Validation &amp; Finalization',['../d4/d4b/software_readme_page.html#autotoc_md52',1,'']]],
  ['finalization_20conditions_5',['2.6. FINALIZATION CONDITIONS',['../d5/d65/agents_cli_management.html#autotoc_md75',1,'']]],
  ['finalization_20current_6',['Phase 1: Documentation &amp; Dictionary Finalization (CURRENT)',['../d1/dcf/apiMaintenance.html#autotoc_md86',1,'']]],
  ['flow_20diagram_20módulos_20interconectados_7',['1. FLOW DIAGRAM (Módulos Interconectados)',['../d1/df9/arch_modules.html#autotoc_md152',1,'']]],
  ['for_20ane_8',['Why GH Actions for ANE?',['../dd/dce/ghActionsCICD.html#autotoc_md132',1,'']]],
  ['for_20ane_20implementation_9',['Next Steps for ANE Implementation',['../dd/dce/ghActionsCICD.html#autotoc_md149',1,'']]],
  ['for_20ane_20project_10',['GitHub Actions CI/CD: Guide for ANE Project',['../dd/dce/ghActionsCICD.html',1,'cowork_section']]],
  ['for_20chatbots_20management_11',['Multiagent for chatbots management',['../d5/d65/agents_cli_management.html',1,'agents_cli_section']]],
  ['for_20co_20workers_12',['Agents CLI — Guide for co-workers',['../index.html',1,'']]],
  ['for_20each_20module_20state_20of_20design_3a_13',['2. Task list for each module/state of design:',['../d5/d65/agents_cli_management.html#autotoc_md64',1,'']]],
  ['for_20our_20repository_14',['3. Specific Use Cases for our Repository',['../dd/dce/ghActionsCICD.html#autotoc_md136',1,'']]],
  ['for_20repository_15',['ADD CI/CD for repository',['../index.html#autotoc_md0',1,'']]],
  ['for_20time_20series_20alignment_16',['Primary Keys (for time-series alignment)',['../d4/d70/dictionary.html#autotoc_md115',1,'']]],
  ['formal_20component_20model_17',['2.2 Logical Design (Formal Component Model)',['../d4/d4b/software_readme_page.html#autotoc_md38',1,'']]],
  ['formal_20model_18',['1.2. Logical Design (formal model)',['../d5/d65/agents_cli_management.html#autotoc_md60',1,'']]],
  ['format_19',['2.5. OUTPUT FORMAT',['../d5/d65/agents_cli_management.html#autotoc_md73',1,'']]],
  ['format_20name_20type_20unit_20description_20source_20importance_2025_20core_20variables_20final_20notes_20on_20unit_20consistency_20and_20primary_20keys_20',['- &lt;strong&gt;DICTIONARY.md&lt;/strong&gt; — Table format (name | type | unit | description | source | importance); ~25 core variables; final notes on unit consistency and primary keys',['../d1/dcf/apiMaintenance.html#autotoc_md89',1,'']]],
  ['formatting_20strong_21',['&lt;strong&gt;2.1 PEP 8 - Formatting&lt;/strong&gt;',['../df/d85/develop_standards.html#autotoc_md173',1,'']]],
  ['fr_22',['1.2 Functional Requirements (FR)',['../d4/d4b/software_readme_page.html#autotoc_md33',1,'']]],
  ['frequency_20monitoring_20signal_20intelligence_20api_23',['ANE Frequency Monitoring &amp; Signal Intelligence API',['../d4/d4b/software_readme_page.html',1,'software_page']]],
  ['functional_20requirements_20fr_24',['1.2 Functional Requirements (FR)',['../d4/d4b/software_readme_page.html#autotoc_md33',1,'']]],
  ['functional_20requirements_20nfr_25',['1.3 Non-Functional Requirements (NFR)',['../d4/d4b/software_readme_page.html#autotoc_md34',1,'']]]
];
