name: Deployment Page

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        type: string
        default: 'User'

  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout codee
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Regenerate Documentation
        shell: pwsh
        run: |
          $greetName = "${{ github.event.inputs.name }}"

          if ([string]::IsNullOrEmpty($greetName)) {
            $greetName = "User"
          }

          Write-Host "Hello $greetName, regenerating web page..."

          if (!(Test-Path "docs")) {
            New-Item -ItemType Directory -Path "docs"
          }

          ./generatedocs.ps1

      # --- Desactivar Jekyll ---
      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to ghPage branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: ghPage
          clean: true
          single-commit: true
          commit-message: "automation: update documentation and disable jekyll"