# This is a basic workflow that is manually triggered

name: deployment page 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: ' u are my 1st person to greet'
        # Default value if no value is explicitly provided
        required: true
        # The data type of the input
        type: string

  push: 
    # Trigger the workflow on push to the main branch
    branches: [main]
  pull request: 
    branches:  [main] 

   
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    
    - name : regenerate web page 
      run : | 
        echo "regenerating web page"
        .\generatedocs.ps1
        git checkout ghPage 
        git clean -fdx
        git rm -rf
        git checkout main -- docs/
        git add .
        git commit -m " automation : regenerate web page" 
        git push origin ghPage
        

